version: "2"
services:
  web:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: hello-mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"